[build]
  functions = "netlify/functions"
  
    [[redirects]]
 from = "/posts/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

  [dev]
  functions = "netlify/functions"

  [[redirects]]
 from = "/posts/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true